language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE
  - TAO_ROOT=$TRAVIS_BUILD_DIR/TAO
  - CIAO_ROOT=$TRAVIS_BUILD_DIR/CIAO
  - DANCE_ROOT=$TRAVIS_BUILD_DIR/DAnCE
  - MPC_ROOT=$TRAVIS_BUILD_DIR/MPC
  - PATH=$ACE_ROOT/lib:$PATH
before_install:
  - git clone git://github.com/DOCGroup/MPC.git

before_script:
  - export
  - echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h
  - if [ "$CXX" == "g++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CXX" == "clang++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi

script:
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -workers 2
  - make -j 2

